---

- name: Generate SSH key pair
  ansible.builtin.openssh_keypair:
    path: "{{ ssh_key_directory }}/id_ed25519"
    type: ed25519
    comment: "Home services"
  register: ssh_key_result

- name: Copy public key to remote hosts
  ansible.builtin.copy:
    content: "{{ ssh_key_result.public_key }}"
    dest: "{{ ssh_key_directory }}/id_ed25519.pub"

- name: Add public key to authorized keys
  ansible.builtin.lineinfile:
    path: "{{ user_home_directory }}/.ssh/authorized_keys"
    line: "{{ ssh_key_result.public_key }}"
    create: yes

- name: Add host key to known hosts
  ansible.builtin.shell:
    cmd: "ssh-keyscan -H {{ ansible_hostname }} >> {{ user_home_directory }}/.ssh/known_hosts"
