---
- name: node-exporter
  hosts: [gomey,floof,biggie]
  become: true

  roles:
      - role: node-exporter
        tags: [ node-exporter ]
      - role: portainer-agent
        tags: [ portainer-agent ]

  # pihole mostly
- name: gomey
  hosts: [gomey]
  become: true
  
  roles:
      - role: pihole
        tags: [ pihole ]
      - role: heimdall
        tags: [ heimdall ]

  # home automation server.
- name: floof
  hosts: [floof]
  become: true
  
  roles:
      - role: home-assistant
        tags: [ home-assistant ]
      - role: zigbee2mqtt
        tags: [ zigbee2mqtt ]
      - role: mosquitto
        tags: [ mosquitto ]
      - role: scrypted
        tags: [ scrypted ]
      - role: zwavejs
        tags: [ zwavejs ]

  # Monitoring services mostly, TODO: merge in internet-pi from geerling
- name: lola
  hosts: [lola]
  become: true

  roles:
      - role: uptime-kuma
        tags: [ uptime-kuma ]
      - role: portainer
        tags: [ portainer ]
      - role: proxy
        tags: [ proxy ]
      - role: vaultwarden
        tags: [ vaultwarden ]

- name: Setup NAS services
  hosts: [nas]
  
  roles:
      - role: media
        tags: [media]
        