---
- name: node-exporter
  hosts: [gomey,floof,biggie,nut-proxy,media]
  become: true

  roles:
      - role: node-exporter
        tags: [ node-exporter ]
      - role: portainer-agent
        tags: [ portainer-agent ]

  # pihole mostly
- name: gomey
  hosts: [gomey]
  become: true
  
  roles:
      - role: pihole
        tags: [ pihole ]
      - role: heimdall
        tags: [ heimdall ]
      - role: tailscale
        tags: [ tailscale ]

  # home automation server.
- name: floof
  hosts: [floof]
  become: true
  
  roles:
      - role: home-assistant
        tags: [ home-assistant ]
      - role: zigbee2mqtt
        tags: [ zigbee2mqtt ]
      - role: mosquitto
        tags: [ mosquitto ]
      - role: scrypted
        tags: [ scrypted ]
      - role: zwavejs
        tags: [ zwavejs ]

  # Monitoring services mostly, TODO: merge in internet-pi from geerling
- name: lola
  hosts: [lola]
  become: true

  roles:
      - role: uptime-kuma
        tags: [ uptime-kuma ]
      - role: portainer
        tags: [ portainer ]
      - role: proxy
        tags: [ proxy ]
      - role: vaultwarden
        tags: [ vaultwarden ]

- name: Setup NAS services
  hosts: [media]
  
  roles:
      - role: media
        tags: [media]

  # pihole backup
- name: pihole-backup
  hosts: [nut-proxy]
  become: true
  
  roles:
      - role: pihole
        FTLCONF_LOCAL_IPV4: 10.0.0.233
        host_name: Secondary pihole
        container_name: SecondaryPihole
        tags: [ secondary-pihole ]
        