---
- hosts: all

  vars:
    username: pi
    docker_dir: /data

  roles:
      - role: security
        tags: [ security ]
      - role: nut-client
        tags: [ nut-client ]
      - role: docker
        tags: [ docker ]
      - role: node-exporter
        tags: [ node-exporter ]
      - role: portainer
        tags: [ portainer ]
      - role: portainer-agent
        tags: [ portainer-agent ]
      - role: pihole
        tags: [ pihole ]
      - role: cloudflared
        tags: [ cloudflared ]


