---
- hosts: all

  vars:
    username: pi
    docker_dir: /data

  roles:
     #- security
      - nut-client
     #- docker
     #- node-exporter
     #- portainer
     #- portainer-agent
     #- pihole
     #- cloudflared

