---
- name: setup nas for backups
  hosts: [nas]
  
  roles:
      - role: setup-nas-for-backups
        tags: [setup-nas-for-backups]

- name: Setup media services
  hosts: [nas]
  
  roles:
      - role: media
        tags: [media]

