---
collections:
  - name: community.docker
    version: ">=4.0.0"
  - name: community.general
    version: ">=11.0.0"
  - name: ansible.posix
    version: ">=2.0.0"
  - name: community.crypto
    version: ">=2.0.0"
