---
- name: base build
  hosts: [service_hosts]
  become: true

  roles:
      - role: security
        tags: [ security ]
      - role: nut-client
        tags: [ nut-client ]
      - role: docker
        tags: [ docker ]

- name: ssh keys
  hosts: [ssh_hosts]
  roles:
      - role: ssh-key-gen
        tags: [ ssh-key-gen ]


- name: ssh-config
  hosts: [service_hosts, nut-proxy]
  tags: [ssh-config]
  vars:
    ssh_key_filename: "id_rsa"
  tasks:
    - name: Add a host in the configuration
      community.general.ssh_config:
        host: "nas"
        hostname: "10.0.0.2"
        identity_file: "~/.ssh/{{ ssh_key_filename }}"
        port: '22'
        identities_only: true
        remote_user: "dmcgough"
        ssh_config_file: ~/.ssh/config

- name: keepalived-master service
  hosts: [gomey]
  become: true

  roles:
      - role: keepalived-master
        tags: [ keepalived-master ]

- name: build nut proxy service
  hosts: [nut-proxy]
  become: true

  roles:
      - role: security
        tags: [ security ]
      - role: nginx-nut-proxy
        tags: [ nginx-nut-proxy ]
      - role: nut-client
        tags: [ nut-client ]
      - role: keepalived-backup
        tags: [ keepalived-backup ]
      - role: docker
        tags: [ docker ]
  tasks:
    - name: Copy nut client configuration files in place.
      template:
        src: "roles/nginx-nut-proxy/templates/{{ item }}.j2"
        dest: "/etc/nut/{{ item }}"
        owner: root
        group: nut
        mode: 0600
      with_items:
        - upssched-cmd

    - name: restart nut-cient
      service:
        name: nut-client
        state: restarted