---
- name: base build
  hosts: [service_hosts]
  become: true

  roles:
      - role: security
        tags: [ security ]
      - role: nut-client
        tags: [ nut-client ]
      - role: docker
        tags: [ docker ]

- name: keepalived-master service
  hosts: [gomey]
  become: true

  roles:
      - role: keepalived-master
        tags: [ keepalived-master ]