---
- name: setup nas for backups
  hosts: [nas]
  
  roles:
      - role: setup-nas-for-backups
        tags: [setup-nas-for-backups]

- name: process service hosts
  hosts: [service_hosts]
  become: true

  vars:
    username: pi
    docker_dir: /data
    backups_dir: /backups

  roles:
      - role: security
        tags: [ security ]
      - role: nut-client
        tags: [ nut-client ]
      - role: docker
        tags: [ docker ]
      - role: node-exporter
        tags: [ node-exporter ]
      - role: portainer
        tags: [ portainer ]
      - role: portainer-agent
        tags: [ portainer-agent ]
      - role: pihole
        tags: [ pihole ]
      - role: cloudflared
        tags: [ cloudflared ]



