---
- hosts: dev
  gather_facts: false

  vars:
    target_user: pi
    target_host: 10.0.0.4
    ssh_key_name: ansible_generated_key123
    ssh_key_path: ~/.ssh/{{ ssh_key_name }}
    known_hosts_path: /home/{{ target_user }}/.ssh/known_hosts

  tasks:
    - name: Generate SSH key pair
      ansible.builtin.openssh_keypair:
        path: "{{ ssh_key_path }}"
        type: rsa
        size: 2048

    - name: Copy public key to target host
      hosts: nut-proxy
      ansible.builtin.copy:
        content: "{{ lookup('file', ssh_key_path + '.pub') }}"
        dest: "~/.ssh/{{ ssh_key_name }}.pub"
        remote_src: true

    - name: Add key to known_hosts
      community.general.known_hosts:
        name: "{{ target_host }}"
        key: "{{ lookup('file', ssh_key_path + '.pub') }}"
        path: "{{ known_hosts_path }}"
        state: present
      become_user: "{{ target_user }}"
