---

- name: Make sure the portainer-agent container is created and running
  community.general.docker_container:
    name: "portainer_agent"
    image: portainer/agent:2.18.2
    pull: yes
    state: "started"
    restart_policy: always
    ports:
      - "9002:9001"
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /var/run/docker.sock:/var/run/docker.sock:ro
  become: false

