---
- name: Create the {{container_name}} config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{container_name}}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the {{container_name}} container is created and running
  community.general.docker_container:
    name: "{{container_name}}"
    image: homeassistant/home-assistant:2023.11.2
    pull: yes
    state: "started"
    privileged: true
    network_mode: "host"
    volumes:
      - "{{ docker_dir }}/{{container_name}}/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    restart_policy: always
  become: false

- name: Make {{container_name}} backup directory
  ansible.builtin.file:
    path: "{{ backups_dir }}/{{container_name}}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy backup script file in place.
  template:
    src: "templates/backup-basic-docker.sh.j2"
    dest: "/usr/local/bin/backup-{{container_name}}.sh"
    owner: root
    group: root
    mode: 0755

- name: Add cron job to run backup weekly, at midnight on Sundays.
  ansible.builtin.cron:
    name: Run {{container_name}}-backup script.
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "/usr/local/bin/backup-{{container_name}}.sh"
    state: present
  become: false