---

- name: Create the {{dave_container_name}} data folder
  ansible.builtin.file:
    path: "{{dave_backup_dir}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create the {{jeni_container_name}} data folder
  ansible.builtin.file:
    path: "{{jeni_backup_dir}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create the {{docker_dir}} config folder
  ansible.builtin.file:
    path: "{{docker_dir}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy docker-compose.yml file in place.
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ docker_dir }}//docker-compose.yml"

- name: Ensure the services are running.
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir }}/"
    build: never
  become: false