---
- name: Install nginx package.
  ansible.builtin.apt:
    name: nginx
    state: present
  become: true

- name: Install nginx extras package.
  ansible.builtin.apt:
    name: nginx-extras
    state: present
  become: true

- name: Ensure line is present in nginx.conf file
  lineinfile:
    path: /etc/nginx/nginx.conf
    line: 'stream { server { listen 3493; proxy_pass 10.0.0.2:3493; } }'
  become: true

- name: Remove default site, we don't need it
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Ensure that nginx service is restarted and enabled on boot
  service:
    name: nginx
    state: restarted
    enabled: true
  become: true
  
  