---
docker_deps:
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'gnupg'
  - 'curl'

docker_packages:
  - 'docker-ce'
  - 'docker-ce-cli'
  - 'containerd.io'
  - 'docker-compose-plugin' 
  - 'docker-ce-rootless-extras'
  - 'docker-buildx-plugin'
