---
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Run the equivalent of "apt-get full-upgrade" as a separate step
  ansible.builtin.apt:
    upgrade: full

- name: Run the equivalent of "apt-get clean" as a separate step
  ansible.builtin.apt:
    clean: true

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: register_name

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
  when: register_name.stat.exists
