---

- name: Install keepalived package.
  ansible.builtin.apt:
    name: keepalived
    state: present
  become: true

- name: Ensure that keepalived service is started and enabled on boot
  service:
    name: keepalived
    state: started
    enabled: true
  become: true

- name: Copy keepalived.conf file in place.
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644