---
- name: Create the portainer config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/portainer"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the portainer container is created and running
  community.general.docker_container:
    name: "portainer"
    image: portainer/portainer-ce:2.17.1
    pull: yes
    state: "started"
    restart_policy: always
    ports:
      - "9443:9443"
      - "8000:8000"
    security_opts:
      "no-new-privileges:true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "{{ docker_dir }}/portainer:/data"

