---

- name: Create the {{container_name}} config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{container_name}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
  register: grpid

- name: Make sure the {{container_name}} container is created and running
  community.general.docker_container:
    name: "{{container_name}}"
    image: jenkins/jenkins:2.530-jdk21
    pull: yes
    state: "started"
    env:
      JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York -Duser.timezone=America/New_York"
    groups:
      - "{{grpid.gid}}"
    ports:
      - 38080:8080
      - 50000:50000
    volumes:
      - "{{ docker_dir }}/{{container_name}}:/var/jenkins_home"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/libexec/docker/cli-plugins/docker-buildx:/usr/libexec/docker/cli-plugins/docker-buildx"
    restart_policy: always
  become: false

- name: Make {{container_name}} backup directory
  ansible.builtin.file:
    path: "{{ backups_dir }}/{{container_name}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy backup script file in place.
  template:
    src: "templates/backup-basic-docker.sh.j2"
    dest: "/usr/local/bin/backup-{{container_name}}.sh"
    owner: root
    group: root
    mode: 0755

- name: Add cron job to run backup weekly, at midnight on Sundays.
  ansible.builtin.cron:
    name: Run {{container_name}}-backup script.
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "/usr/local/bin/backup-{{container_name}}.sh"
    state: present
  become: false