---
- name: Create the {{container_name}} config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{container_name}}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Make sure the {{container_name}} container is created and running
  community.general.docker_container:
    name: "{{container_name}}"
    image: jenkins/jenkins:2.395-jdk11
    pull: yes
    state: "started"
    ports:
      - 38080:8080
      - 50000:50000
    volumes:
      - "{{ docker_dir }}/{{container_name}}:/var/jenkins_home"
    restart_policy: always
  become: false

- name: Make {{container_name}} backup directory
  ansible.builtin.file:
    path: "{{ backups_dir }}/{{container_name}}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy backup script file in place.
  template:
    src: "backup-{{container_name}}.sh.j2"
    dest: "/usr/local/bin/backup-{{container_name}}.sh"
    owner: root
    group: root
    mode: 0755

- name: Add cron job to run backup weekly, at midnight on Sundays.
  ansible.builtin.cron:
    name: Run {{container_name}}-backup script.
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "/usr/local/bin/backup-{{container_name}}.sh"
    state: present
  become: false