---
- name: Install nut-client
  ansible.builtin.apt:
    update_cache: yes
    name: nut-client
    state: present

- name: Copy nut client configuration files in place.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    owner: root
    group: nut
    mode: 0600
  with_items:
    - nut.conf
    - upsmon.conf
    - upssched-cmd
    - upssched.conf

- name: make upssched-cmd executable.
  ansible.builtin.file:
    path: /etc/nut/upssched-cmd
    mode: '0755'

- name: Ensure that nut-client service is restarted and enabled on boot
  service:
    name: nut-client
    state: restarted
    enabled: true

- name: Ensure that nut client can connect to nut server
  ansible.builtin.command: upsc {{ ups_name }}@{{ nut_server }}
  register: upsc_output

# todo: check output to ensure it's expected.
- name: Print output
  debug:
    msg: "{{upsc_output}}"
