---
- name: Install nut-client
  ansible.builtin.package:
    name: nut-client
    state: present

- name: Copy nut.conf file
  ansible.builtin.copy:
    src: resources/nut-client/nut.conf
    dest: /etc/nut/nut.conf
    mode: preserve

- name: Copy upsmon.conf file
  ansible.builtin.copy:
    src: resources/nut-client/upsmon.conf
    dest: /etc/nut/upsmon.conf
    mode: preserve

- name: Copy upssched-cmd file with execute permissions
  ansible.builtin.copy:
    src: resources/nut-client/upssched-cmd
    dest: /etc/nut/upssched-cmd
    owner: root
    group: nut
    mode: '0655'

- name: Copy upssched.conf file
  ansible.builtin.copy:
    src: resources/nut-client/upssched.conf
    dest: /etc/nut/upssched.conf
    mode: preserve
  notify: restart nut-client

- name: Ensure that nut-client service is started and enabled on boot
  service:
    name: nut-client
    state: started
    enabled: true

  
- name: Ensure that nut client can connect to nut server
  ansible.builtin.command: upsc {{ ups_name }}@{{ nut_server }}
  register: upsc_output

# todo: check output to ensure it's expected.
- name: Print output
  debug:
    msg: "{{upsc_output}}"
