---
- name: Create the {{container_name}} config folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{container_name}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Make sure the {{container_name}} container is created and running
  community.general.docker_container:
    name: "{{container_name}}"
    image: koush/scrypted@sha256:a6e3233c89c40e419f81d88673e5426b9f526cf5aaacac19c73f3fb4957e7f3c
    pull: yes
    state: "started"
    network_mode: host
    env:
      SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: "SFKGJFJFJFKSFSKFWPWWPRRHHDH"
      SCRYPTED_WEBHOOK_UPDATE: "http://localhost:10444/v1/update"
    volumes:
      - "{{ docker_dir }}/{{container_name}}:/server/volume"
    restart_policy: always
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "10"
  become: false

- name: Make {{container_name}} backup directory
  ansible.builtin.file:
    path: "{{ backups_dir }}/{{container_name}}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Copy backup script file in place.
  template:
    src: "templates/backup-basic-docker.sh.j2"
    dest: "/usr/local/bin/backup-{{container_name}}.sh"
    owner: root
    group: root
    mode: 0755

- name: Add cron job to run backup weekly, at midnight on Sundays.
  ansible.builtin.cron:
    name: Run {{container_name}}-backup script.
    minute: "0"
    hour: "0"
    weekday: "0"
    job: "/usr/local/bin/backup-{{container_name}}.sh"
    state: present
  become: false