---
backup_dirs: 
  - '/volume1/backups/pihole' 
  - '/volume1/backups/home-assistant' 
  - '/volume1/backups/zigbee2mqtt'
  - '/volume1/backups/mosquitto'
  - '/volume1/backups/uptime-kuma'  
  - '/volume1/backups/scrypted'
  - '/volume1/backups/heimdall'
  - '/volume1/backups/nginx-proxy-manager'
  - '/volume1/backups/vaultwarden'
  - '/volume1/backups/jenkins'
  - '/volume1/backups/media'
  - '/volume1/backups/media/jellyfin'
  - '/volume1/backups/media/prowlarr'
  - '/volume1/backups/media/qbt'
  - '/volume1/backups/media/radarr'
  - '/volume1/backups/media/sabnzbd'
  - '/volume1/backups/media/sonarr'
  - '/volume1/backups/SecondaryPihole'
  - '/volume1/backups/zwavejs2mqtt'
