---
- name: restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart ssh
  service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_ssh_restart_handler_state }}"
