---
- name: Make sure the cloud-flared container is created and running
  community.general.docker_container:
    name: "cloudflared-tunnel"
    image: cloudflare/cloudflared:2023.8.1
    pull: yes
    state: "started"
    command:
      - 'tunnel'
      - 'run' 
      - '--token'
      - '{{TUNNEL_TOKEN}}'
    restart_policy: always
  become: false
    
