---

- name: Prune everything
  community.docker.docker_prune:
    containers: true
    containers_filters:
      # only consider containers created more than 24 hours ago
      until: 24h
    images: true
    images_filters:
      dangling: true
    networks: true
    volumes: true
    builder_cache: true